on: [push]

jobs:
  my_little_job:
    runs-on: ubuntu-latest
    name: A simple sample of composite
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: vinnimous/sample-composite-action@v1
        with:
          project: 'Something'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
